home/urls.py
from django.urls import path

from . import views

app_name = 'learning_logs'

urlpatterns = [
    path('', views.index, name='index'),
    path("faq/", views.faq, name="faq"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("privacy/", views.privacy, name="privacy"),
    path("terms/", views.terms, name="terms"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.text[:50]}..."

home/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings


def index(request):
    s = False
    if request.method == 'POST':
        if "contact-form" in request.POST.keys():
            messages = request.POST['contact-name'] + "\n" + \
                       request.POST['contact-email'] + "\n" + \
                       request.POST['contact-message']

            send_mail("CONTACT FORM",
                      messages,
                      settings.EMAIL_HOST_USER,
                      ['support@fast-recovery.org'],
                      fail_silently=False
                      )
            s = True
        elif "send-message" in request.POST.keys():
            messages = request.POST['send-name'] + "\n" + \
                       request.POST['send-email'] + "\n" + \
                       request.POST['text']

            send_mail("SEND MESSAGE FORM",
                      messages,
                      settings.EMAIL_HOST_USER,
                      ['support@fast-recovery.org'],
                      fail_silently=False
                      )
            s = True

        else:
            messsages = request.POST["ex-name"] + "\n" + \
                        request.POST["ex-company"] + "\n" + \
                        request.POST["ex-phone"] + "\n" + \
                        request.POST["ex-email"] + "\n" + \
                        request.POST["ex-currency"] + "\n" + \
                        request.POST["ex-amount"] + "\n" + \
                        request.POST["ex-country"] + "\n" + \
                        request.POST["ex-message"]

            send_mail("EXAMINATION FORM",
                      messsages,
                      settings.EMAIL_HOST_USER,
                      ["support@fast-recovery.org"],
                      fail_silently=False
                      )
            s = True

    return render(request, 'home/base.html', {"s": s})


def faq(request):
    s = False
    if request.method == 'POST':
        if "send-message" in request.POST.keys():
            messages = request.POST['send-name'] + "\n" + \
                       request.POST['send-email'] + "\n" + \
                       request.POST['text']

            send_mail("SEND MESSAGE FORM",
                      messages,
                      settings.EMAIL_HOST_USER,
                      ['support@fast-recovery.org'],
                      fail_silently=False
                      )
            s = True
    return render(request, "home/faq.html", {"s": s})


def about(request):
    s = False
    if request.method == 'POST':
        if "send-message" in request.POST.keys():
            messages = request.POST['send-name'] + "\n" + \
                       request.POST['send-email'] + "\n" + \
                       request.POST['text']

            send_mail("SEND MESSAGE FORM",
                      messages,
                      settings.EMAIL_HOST_USER,
                      ['support@fast-recovery.org'],
                      fail_silently=False
                      )
            s = True
    return render(request, "home/about.html", {"s": s})


def contact(request):
    s = False
    if request.method == 'POST':
        if "contact-form" in request.POST.keys():
            messages = request.POST['contact-name'] + "\n" + \
                       request.POST['contact-email'] + "\n" + \
                       request.POST['text']

            send_mail("CONTACT FORM",
                      messages,
                      settings.EMAIL_HOST_USER,
                      ['support@fast-recovery.org'],
                      fail_silently=False
                      )
            s = True
        elif "send-message" in request.POST.keys():
            messages = request.POST['send-name'] + "\n" + \
                       request.POST['send-email'] + "\n" + \
                       request.POST['text']

            send_mail("SEND MESSAGE FORM",
                      messages,
                      settings.EMAIL_HOST_USER,
                      ['support@fast-recovery.org'],
                      fail_silently=False
                      )
            s = True
    return render(request, "home/contact.html", {"s": s})


def privacy(request):
    context = {

    }
    return render(request, "home/privacy.html", context)


def terms(request):
    context = {

    }
    return render(request, "home/terms.html", context)

home/templates/home/about.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>about</title>
    <script src="{% static "js/jquery-3.6.0.min.js" %}"></script>
    <script src="{% static "js/sweetalert.min.js" %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <script src="{% static "js/jquery-3.6.0.min.js" %}"></script>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="{% static "js/all.js" %}" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
</head>
<body>

<script> {% if s %} swal("Your form submitted successfully!", "", "success");
{% endif %}
</script>


{% include "home/navbar.html" %}
<!-- About-->
<br>
<br>
<br>
<br>
<br>
<section class="page-section" id="ABOUT US"
         style="font-size: 2rem!important;font-weight: normal!important;font-style:normal;!important;">
    <div class="container">
        <div class="text-center  section-title">
            <h2 class="section-heading text-uppercase" style="font-size: 32px;font-weight: 700;">ABOUT US</h2>
            <br>
            <h3 class="section-subheading text-muted"
                style="font-size: 1rem!important;font-style: normal; text-align: left">

                <p>Are you still waiting for your money from a broker?

                    We'd like to hear from you - what you tell us can help others.</p>


                <p>Filling simple from will help us to get your case correctly and use all our abilities and
                    professionality to recover your money.

                    Our competent lawyers will take care of your accident and
                    provide you with all recent updates of your case.</p>


                <p>We will use this information to help fight against notorious companies and create reports to close
                    their activity.


                    Just fill the form and our lawyer department will connect with you within next 24 hours and give a
                    consultation.</p>
            </h3>
        </div>
        <h2 style="margin-bottom: .5rem;font-weight: 500;line-height: 1.2;">What you can expect from us</h2>
        <p style="font-size: 1rem;font-weight: 400;line-height: 1.5;">When you deal with us you can expect:</p>
        <ul style="font-size: 1rem;font-weight: 400;line-height: 1.5;">
            <li>timely, accurate and accessible service</li>
            <li>to be dealt with fairly and courteously</li>
            <li>to have your privacy rights respected</li>
            <li>that we will advise you of waiting times, and of a time frame for the progress or completion of your
                complaint
            </li>
            <li>that we will provide you with an explanation of our procedures, and what we can and cannot do</li>
            <li>that we will identify ourselves when talking or writing to you</li>
            <li>that we will answer your enquiry or transfer your call to the appropriate person</li>
            <li>that if your issue is outside our area of authority and it is possible to refer you to another agency,
                we will do so
            </li>
            <li>our facilities to be safe and accessible</li>
            <li>that we will have special regard for the needs of vulnerable and disadvantaged customers</li>
            <li>that we will advise you of any appeal rights that you may have.</li>
        </ul>
    </div>
</section>

<!-- ======= Footer ======= -->
<footer id="footer" style="background-color: #111;color: #fff;margin: 0px!important;">

    <div class="footer-top" style="padding-top: 30px">
        <div class="container">
            <div class="row">

                <div class=" footer-contact" style="width: 25%">
                    <h3>Fast-Recovery</h3>
                    <p>
                        <i class="bx bx-chevron-right"></i> <a href="{% url "learning_logs:privacy" %}">Privacy
                        policy</a><br>
                        <i class="bx bx-chevron-right"></i> <a href="{% url "learning_logs:terms" %}">Terms and
                        Conditions</a>
                    </p>
                </div>

                <div class="footer-contact" style="width: 50%">
                    <strong>DISCLAIMER</strong><br>
                    <div style="padding-top: 1em">
                        <p>1. Fast-Recovery provides consultations. Chargeback and other Fast recovery programs
                            contracted thereafter are subject to retainers, fees and/or commissions depending on
                            the
                            individual case history and the type of service selected Fast-Recovery does not
                            offer any
                            financial investments or advice.</p>
                        <p>2. Residents in the United Kingdom: Fast-Recovery does not assist and/or advise
                            consumers
                            with complaints in relation to mis-sold investment products which have been
                            purchased from
                            firms regulated by the UK Prudential Regulation Authority (PRA) and/or the UK
                            Financial
                            Conduct Authority (FCA).</p>
                    </div>

                </div>

                <div class="footer-contact" style="float: right; width: 25%">
                    <strong>Email:</strong> support@fast-recovery.org<br>

                </div>
            </div>
        </div>
    </div>

    <div class="container text-center py-4">

        <div class="mr-md-auto text-center">
            <div class="copyright">
                © <span id="currentYear"></span> <strong><span>Fast-Recovery</span></strong>. All Rights
                Reserved
            </div>
        </div>

        <script>
            let d = new Date();
            let n = d.getFullYear();
            document.getElementById('currentYear').innerText = n;
        </script>
    </div>
</footer>

{% include "home/sendmessage.html" %}

</body>
</html>

home/templates/home/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<!-- Navigation-->
<nav style="background-color:white;box-shadow: 0 2px 15px rgba(0,0,0,.1)"
     class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">

        <a class="navbar-brand" href="{% url "learning_logs:index" %}"><img
                src="{% static 'assets/img/navbar-logo.svg' %}" alt="..."/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu

            <a href="javascript:void(0);" class="icon" onclick="myFunction()"><i class="fas fa-bars ms-1"></i></a>

        </button>

        <div style="background-color: white" class="collapse navbar-collapse" id="navbarResponsive">


            <ul style="background-color:white;font-weight: 600;font-family: Roboto,sans-serif;font-size: 13px!important;"
                class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url "learning_logs:about" %}">ABOUT US</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url "learning_logs:contact" %}">Contact</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url "learning_logs:faq" %}">FAQ</a></li>
            </ul>
        </div>


    </div>
</nav>
<script>
    function myFunction() {
        var x = document.getElementById("navbarResponsive");
        if (x.style.display === "block") {
            x.style.display = "none";
        } else {
            x.style.display = "block";
        }
    }
</script>

home/templates/home/privacy.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>privacy</title>
    <script src="{% static "js/jquery-3.6.0.min.js" %}"></script>
    <script src="{% static "js/sweetalert.min.js" %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <script src="{% static "js/jquery-3.6.0.min.js" %}"></script>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="{% static "js/all.js" %}" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">

</head>
<body>



!-- Navigation-->
{% include "home/navbar.html" %}

<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

        <!-- Uncomment below if you prefer to use an image logo -->

        <a href="{% url "learning_logs:index" %}" class="logo mr-auto">

            <img src="assets/img/logo.png" alt="" class="img-fluid">

        </a>
    </div>

</header><!-- End Header -->

<!-- ======= Hero Section ======= -->
<main id="main">
    <br>

    <!-- ======= Services Section ======= -->
    <section id="services" class="services section-bg" style="margin-top: 40px">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2 style="text-align: center">Privacy Policy</h2>
            </div>

            <p>Your privacy is important to us. It is&nbsp;<strong><a
                    style="text-decoration: underline; color: #211f40;"
                    href="{% url "learning_logs:index" %}">Fast-Recovery</a>’s</strong> policy to respect your
                privacy regarding any
                information we may collect from you across our website,&nbsp; <strong><a
                        style="color: #211f40; text-decoration: underline;" href="{% url "learning_logs:index" %}">https://http://fast-recovery.org/</a></strong>&nbsp;,
                and other sites we own and operate. We only ask for personal information when we truly need it to
                provide a service to you.</p>
            <p>We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re
                collecting it and how it will be used. We only retain collected information for as long as necessary to
                provide you with your requested service. What data we store, we’ll protect within commercially
                acceptable means to prevent loss and theft, as well as unauthorised access, disclosure, copying, use or
                modification. We don’t share any personally identifying information publicly or with third-parties,
                except when required to by law. Our website may link to external sites that are not operated by us.
                Please be aware that we have no control over the content and practices of these sites, and cannot accept
                responsibility or liability for their respective privacy policies. You are free to refuse our request
                for your personal information, with the understanding that we may be unable to provide you with some of
                your desired services.</p>
            <p>Your continued use of our website will be regarded as acceptance of our practices around privacy and
                personal information. If you have any questions about how we handle user data and personal information,
                feel free to contact us.</p>

        </div>
    </section><!-- End Services Section -->

</main><!-- End #main -->

<!-- ======= Footer ======= -->
<footer id="footer" style="position: fixed; bottom: 0; width: 100%;background-color: #111;color: #fff">

    <div class="container d-md-flex py-4">

        <div class="mr-md-auto text-center text-md-left">
            <div class="copyright">
                &copy; Copyright <strong><span>Fast-Recovery</span></strong>. All Rights Reserved
            </div>
        </div>
    </div>
</footer><!-- End Footer -->


</body>
</html>

home/templates/home/sendmessage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<button style="background-color:blue;padding: 5px;border-radius: 15px;width: 150px" class="open-button"
        onclick="openForm()">Send Massage
</button>

<div class="form-popup" id="myForm">
    <div type="button" style="color: black;width: 1em;font-size: 30px" id="close" onclick="closeForm()">x</div>

    <form action="" method="post" class="form-container">
        {% csrf_token %}
        <p style="text-align: center;color: white">Please fill out the form below<br> and we will get back to you as
            soon as
            possible.</p>


        <input type="text" placeholder="*Name" name="send-name" required>


        <input type="text" placeholder="*Email" name="send-email" required>

        <textarea style="height: 120px;background-color: white;width: 100%;" type="text" placeholder="*Massage"
                  name="text" required></textarea>

        <button type="submit" name="send-message" class="btn" style="color: black!important;">Send Message</button>
        <!-- <button type="button" class="btn cancel" onclick="closeForm()">Close</button> -->
        <!-- <button type="button" class="btn cancel" onclick="closeForm()">Close</button> -->
    </form>
</div>

<script>
    function openForm() {
        document.getElementById("myForm").style.display = "block";
    }

    function closeForm() {
        document.getElementById("myForm").style.display = "none";
    }
</script>